baseURL = "http://tilkov.com/"
languageCode = "en-us"
title = "Minimal"
theme = "minimal"

[params]
    author = "Stefan Tilkov"
    description = "Personal blog"
    githubUsername = "stilkov"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:stefan@tilkov.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/stilkov/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/stilkov/"
    name = "twitter"
    weight = 3
